/** @format */
"use client";

import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/Navbar";

import { Providers } from "./providers";

import { Inter } from "next/font/google";
import { Container } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='bg-slate-800'>
        {" "}
        <Providers>
          <Container maxW={"container.xl"}>
            <Navbar />

            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
